spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/freemix
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      port: 27017
      database: freemix
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8888