spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/freemix
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      port: 27017
      database: freemix
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liOK5XFcdhjSuZDB
            clientSecret: 510b7bb65f0e01ccf5c09271cf96f49a9ef81aa7
            scope: read:user,user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

server:
  port: 8888

logging:
  level:
    org:
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG